language: python
sudo: required

cache:
  directories:
    - $HOME/.theano
    - $HOME/miniconda2
    - $HOME/miniconda3

addons:
  apt_packages:
    - pandoc

before_install:
  - . ./scripts/install_miniconda.sh
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=":99.0"
  - export MKL_THREADING_LAYER=GNU

install:
  - . ./scripts/create_testenv.sh
  - pip install coveralls travis-sphinx==2.0.0

env:
  - PYTHON_VERSION=2.7 FLOATX='float32' TESTCMD="--durations=10 --cov-append"
  - PYTHON_VERSION=2.7 FLOATX='float32' RUN_PYLINT="true" TESTCMD="--durations=10 --cov-append"
  - PYTHON_VERSION=2.7 FLOATX='float32' TESTCMD="--durations=10 --cov-append"
  - PYTHON_VERSION=2.7 FLOATX='float32' TESTCMD="--durations=10 --cov-append"
  - PYTHON_VERSION=2.7 FLOATX='float64' TESTCMD="--durations=10"
  - PYTHON_VERSION=2.7 FLOATX='float64' RUN_PYLINT="true" TESTCMD="--durations=10 --cov-append"
  - PYTHON_VERSION=2.7 FLOATX='float64' TESTCMD="--durations=10 --cov-append"
  - PYTHON_VERSION=3.6 FLOATX='float64' TESTCMD="--durations=10 --cov-append"
  - PYTHON_VERSION=3.6 FLOATX='float64' TESTCMD="--durations=10 --cov-append"
  - PYTHON_VERSION=3.6 FLOATX='float64' BUILD_DOCS="true" TESTCMD="--durations=10 --cov-append"
  - PYTHON_VERSION=3.6 FLOATX='float64' TESTCMD="--durations=10 --cov-append pmlearn/tests/test_base.py"

script:
  - . ./scripts/test.sh $TESTCMD
  - . ./scripts/confirm_mpl_optional.sh

after_success:
  - coveralls